services:
  redis:
    image: acrcryptgeonfc001.azurecr.io/redis:latest
    # Set a size limit. See link below on how to customise.
    # https://redis.io/docs/manual/eviction/
    # command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru

  app:
    image: acrcryptgeonfc001.azurecr.io/mysecret:latest
    depends_on:
      - redis
    environment:
      # Size limit for a single note.
      SIZE_LIMIT: 200 MiB
      THEME_IMAGE: https://www.silaexpert01.fr/welcome.png
      THEME_TEXT: "Envoyez des notes et des fichiers chiffrés."
      THEME_LANGUAGE: FR
      THEME_FAVICON: https://www.silae.fr/wp-content/themes/silae/assets/favicon/favicon-32x32.png
      THEME_PAGE_TITLE: "Mysecret"
    ports:
      - 80:8000

    # Optional health checks
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/api/live/"]
    #   interval: 1m
    #   timeout: 3s
    #   retries: 2
    #   start_period: 5s
